/// Flutter icons TA2Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TA2Icons
///      fonts:
///       - asset: fonts/TA2Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TA2Icons {
  TA2Icons._();

  static const _kFontFam = 'TA2Icons';
  static const String? _kFontPkg = null;

  static const IconData profile_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unchecklist = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_profile = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laporan = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_report = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
